import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home Page</h1>

      <a href="/frogs">Frogs normal link</a>
      <hr />
      <Link href="/frogs">Frogs</Link>
    </>
  );
}
